### ISSUE TITLE
fix footer icon links

### ISSUE THREAD

**Issue by greenMakaroni** [oraichain/oraiscan-frontend#905]
file src/components/Footer\Footer/Footer.js

"a" tag at line 192, which nests GitHubIcon current link in a href property leads to coingecko site, change it to https://github.com/oraichain

"a" tag at line 189, hosting DiscordIcon also leads to coingecko, couldn't find discord link.

**Comment by haunv3** [comment]
> file src/components/Footer\Footer/Footer.js
> 
> "a" tag at line 192, which nests GitHubIcon current link in a href property leads to coingecko site, change it to https://github.com/oraichain
> 
> "a" tag at line 189, hosting DiscordIcon also leads to coingecko, couldn't find discord link.

Thanks for the contribution. we will update it again!
